version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: francescoxx/node_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_db
      - PG_USER=mavi
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db
    command: ["/wait-for-it.sh", "node_db:5432", "--", "node", "index.js"]
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_db
      - POSTGRES_USER=mavi
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}